import * as React from "react"

export const Blank = () => (
    <div>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
    </div>
)
