import * as React from "react"

import { Link } from "react-router-dom"

export const Blank = () => (
    <div>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>This is a blank page. Haha.</p>
        <p>
            Screw this, I'm going <Link to="/">home</Link>.
        </p>
    </div>
)
